import {useEffect,useState} from 'react';
import PrivatePanel from '../../../components/PrivatePanel';
export {getServerSideProps} from '../[tenantId]';
function Overview({tenantId,user}){
  const [data,setData]=useState(null),[error,setError]=useState('');
  useEffect(()=>{let stopped=false;user.getIdToken().then(token=>fetch(`/api/tenants/${tenantId}/overview`,{headers:{Authorization:`Bearer ${token}`}})).then(async res=>{const result=await res.json();if(!res.ok)throw new Error(result.error);if(!stopped)setData(result);}).catch(err=>{if(!stopped)setError(err.message);});return()=>{stopped=true;};},[tenantId,user]);
  return <>{!data&&!error&&<p role="status">Cargando resumen…</p>}{data&&<><p className="hint">Últimos 30 días · {data.from.split('-').reverse().join('/')} al {data.to.split('-').reverse().join('/')}</p><div className="metrics">{[['Reservas',data.total],['Personas reservadas',data.people],['Llegaron',data.arrived],['No asistieron',data.noShow],['Canceladas',data.cancelled],['Reservas hoy',data.today]].map(([label,total])=><section className="box" key={label}><strong>{total}</strong><p>{label}</p></section>)}</div><section className="box"><h2>Origen de las reservas</h2>{data.sources.map(value=><p key={value.source}>{({link:'Link público',manual:'Carga manual',walkin:'Llegadas sin reserva'})[value.source]}: <strong>{value.total}</strong></p>)}</section><section className="box"><h2>Operación del local</h2><p>Configurá mesas, sectores, distribuciones y turnos desde el Admin. La operación diaria se realiza en el Dashboard.</p><a href={`/admin/${tenantId}`}>Configurar local →</a></section></>}{error&&<p className="error" role="alert">{error}</p>}<style jsx>{`.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px}.metrics strong{font-size:32px}.metrics .box{margin-top:0}`}</style></>;
}
export default function Home({tenantId}){return <PrivatePanel tenantId={tenantId} title="Admin">{user=><Overview tenantId={tenantId} user={user}/>}</PrivatePanel>;}
