import {useRef,useState} from 'react';
import {tableLayout} from '../lib/guest-center.mjs';
export default function FloorEditor({tenantId,tables,onChange}){
 const board=useRef(null),drag=useRef(null),[sector,setSector]=useState('');
 const sectors=[...new Set(tables.map(table=>table.sector || 'Sin sector'))];
 function move(index,x,y){const layout=tableLayout(tenantId,tables[index],index,tables.length);onChange(tables.map((table,i)=>i===index?{...table,layout:{...layout,x:Math.max(5,Math.min(95,x)),y:Math.max(5,Math.min(95,y))}}:table));}
 function start(event,index){event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);const rect=board.current.getBoundingClientRect(),layout=tableLayout(tenantId,tables[index],index,tables.length);drag.current={index,dx:event.clientX-rect.left-layout.x*rect.width/100,dy:event.clientY-rect.top-layout.y*rect.height/100};}
 function pointer(event){if(!drag.current)return;const rect=board.current.getBoundingClientRect(),{index,dx,dy}=drag.current;move(index,(event.clientX-rect.left-dx)*100/rect.width,(event.clientY-rect.top-dy)*100/rect.height);}
 return <section className="box"><div className="section-head"><h2>Editor del plano</h2><select aria-label="Sector del plano" value={sector} onChange={e=>setSector(e.target.value)}><option value="">Todos los sectores</option>{sectors.map(value=><option key={value}>{value}</option>)}</select></div><p className="hint">Arrastrá cada mesa para ubicarla. También podés seleccionarla con Tab y moverla con las flechas. Guardá los cambios para actualizar el Dashboard.</p><div className="scroll"><div ref={board} className="board">{tables.map((table,index)=>{if(sector&&(table.sector || 'Sin sector')!==sector)return null;const layout=tableLayout(tenantId,table,index,tables.length);return <button key={index} type="button" className={`table ${layout.shape} ${table.enabled===false?'disabled':''}`} style={{left:`${layout.x}%`,top:`${layout.y}%`}} aria-label={`Mover mesa ${table.name}, ${table.seats} lugares`} onPointerDown={e=>start(e,index)} onPointerMove={pointer} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={e=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();move(index,layout.x+delta[0],layout.y+delta[1]);}}}><strong>{table.name || 'Sin nombre'}</strong><small>{table.seats} lugares</small></button>;})}</div></div><style jsx>{`.scroll{overflow:auto}.board{position:relative;min-width:620px;height:620px;background:radial-gradient(#e8dece 1px,transparent 1px);background-size:24px 24px;margin:24px 0}.table{position:absolute;transform:translate(-50%,-50%);width:76px;height:76px;padding:6px;border:2px solid #dd6e78;background:#ffe0e2;color:#281f18;display:flex;flex-direction:column;align-items:center;justify-content:center;cursor:grab;touch-action:none;user-select:none;gap:5px}.table:active{cursor:grabbing}.round{border-radius:50%}.square{border-radius:9px}.table small{font-size:10px}.disabled{opacity:.4}select{max-width:220px}`}</style></section>;
}
