const days = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'];
export default function OperatingHoursEditor({ value, onChange }) {
  const rules = value || [];
  function update(index, patch) { onChange(rules.map((rule, i) => i === index ? { ...rule, ...patch } : rule)); }
  function range(index, rangeIndex, patch) { update(index, { ranges: rules[index].ranges.map((item, i) => i === rangeIndex ? { ...item, ...patch } : item) }); }
  return <section className="box" id="horarios-operacion">
    <div className="section-head"><h2>Horarios de operación</h2>{value !== null && value !== undefined && <button type="button" className="secondary" onClick={() => onChange([...rules, { id: crypto.randomUUID(), name: '', type: 'opening', enabled: true, ranges: [{ from: '12:00', to: '15:30' }], days: [], dates: [], startDate: null, endDate: null }])}>Crear horario</button>}</div>
    <p className="hint">Definí cuándo abre y cierra el local. Los horarios de llegada de las reservas se configuran por separado, en Turnos de reserva.</p>
    {value == null ? <><p className="hint">Todavía no configuraste apertura y cierre. Se mantienen los turnos actuales.</p><button type="button" className="secondary" onClick={() => onChange([])}>Configurar apertura y cierre</button></> : <>
      {!rules.length && <p role="status">Agregá un horario de apertura. Hasta entonces, no habrá horarios disponibles para nuevas reservas.</p>}
      {rules.map((rule, index) => <div className="slot" key={rule.id}>
        <div className="row"><label className="field">Nombre<input required maxLength="100" value={rule.name} onChange={e => update(index, { name: e.target.value })} placeholder="Almuerzo, cena, cierre…" /></label><label className="field">Tipo<select value={rule.type} onChange={e => update(index, { type: e.target.value })}><option value="opening">Horario de apertura</option><option value="closure">Cierre programado</option></select></label><button type="button" className="remove" aria-label={`Quitar horario ${rule.name || index + 1}`} onClick={() => onChange(rules.filter((_, i) => i !== index))}>Quitar</button></div>
        <label className="enabled"><input type="checkbox" checked={rule.enabled} onChange={e => update(index, { enabled: e.target.checked })} />Horario activo</label>
        <h3>Rangos horarios</h3>{rule.ranges.map((item, i) => <div className="row" key={i}><label className="field">Desde<input type="time" required value={item.from} onChange={e => range(index, i, { from: e.target.value })} /></label><label className="field">Hasta{item.to === '24:00' ? <input value="24:00" readOnly aria-label="Hasta medianoche" /> : <input type="time" required value={item.to} onChange={e => range(index, i, { to: e.target.value })} />}</label><label className="midnight"><input type="checkbox" checked={item.to === '24:00'} onChange={e => range(index, i, { to: e.target.checked ? '24:00' : '23:00' })} />Hasta medianoche</label><button type="button" className="remove" disabled={rule.ranges.length === 1} aria-label={`Quitar rango ${i + 1} de ${rule.name}`} onClick={() => update(index, { ranges: rule.ranges.filter((_, n) => n !== i) })}>Quitar rango</button></div>)}
        <button type="button" className="secondary" onClick={() => update(index, { ranges: [...rule.ranges, { from: '19:00', to: '24:00' }] })}>Agregar rango</button>
        <h3>Días de la semana</h3><div className="days">{days.map((label, day) => <label key={day}><input type="checkbox" checked={rule.days.includes(day)} onChange={e => update(index, { days: e.target.checked ? [...rule.days, day] : rule.days.filter(d => d !== day) })} />{label}</label>)}</div><p className="hint">Se repite cada semana en los días seleccionados.</p>
        <details><summary>Vigencia y fechas puntuales</summary><div className="row validity"><label className="field">Comienza<input type="date" value={rule.startDate || ''} onChange={e => update(index, { startDate: e.target.value || null })} /><small className="hint">Vacío: sin límite de inicio.</small></label><label className="field">Termina<input type="date" value={rule.endDate || ''} onChange={e => update(index, { endDate: e.target.value || null })} /><small className="hint">Vacío: nunca.</small></label></div>
          <p className="hint">Las fechas puntuales agregan días al horario, dentro de su vigencia. Para un horario puntual, dejá los días semanales sin seleccionar.</p>
          {rule.dates.map((date, i) => <div className="row" key={i}><label className="field">Fecha puntual<input type="date" required value={date} onChange={e => update(index, { dates: rule.dates.map((d, n) => n === i ? e.target.value : d) })} /></label><button type="button" className="remove" onClick={() => update(index, { dates: rule.dates.filter((_, n) => n !== i) })}>Quitar fecha</button></div>)}<button type="button" className="secondary" onClick={() => update(index, { dates: [...rule.dates, ''] })}>Agregar fecha puntual</button>
        </details>
      </div>)}
    </>}
    <style jsx>{`h3{font-size:15px;margin:24px 0 12px}.enabled,.midnight{display:flex;align-items:center;gap:8px;font-size:14px;min-height:46px}.enabled input,.midnight input{width:18px;height:18px}.validity{margin-top:20px}summary{cursor:pointer;font-weight:600;margin:20px 0}small{font-weight:400}`}</style>
  </section>;
}
