import { useState } from 'react';
export default function RoomSettingsEditor({ value, onChange }) {
  const [turn, setTurn] = useState({ name: '', from: '20:00', to: '23:00', every: 30, duration: 90, days: [], layoutId: '' });
  const [error, setError] = useState('');
  const layouts = value.layouts || [];
  const booking = { publicEnabled: true, maxAdvanceDays: 90, minNoticeMinutes: 0, maxPartySize: 100, policy: '', ...value.booking };
  const changeLayout = (index, patch) => onChange({ layouts: layouts.map((layout, i) => i === index ? { ...layout, ...patch } : layout) });
  function addTurn() {
    const minutes = time => Number(time.split(':')[0]) * 60 + Number(time.split(':')[1]);
    const from = minutes(turn.from), to = minutes(turn.to);
    if (!turn.name.trim() || !turn.days.length || !Number.isFinite(from) || !Number.isFinite(to) || from > to || !Number.isInteger(turn.every) || turn.every < 15 || !Number.isInteger(turn.duration) || turn.duration < 15 || turn.duration > 720) { setError('Completá nombre, días, rango y duración del turno.'); return; }
    const slots = [];
    for (let minute = from; minute <= to; minute += turn.every) {
      const time = `${String(Math.floor(minute / 60)).padStart(2, '0')}:${String(minute % 60).padStart(2, '0')}`;
      if (value.slots.some(slot => slot.type === 'weekly' && slot.time === time && slot.days.some(day => turn.days.includes(day)))) { setError('Ya existe un horario dentro de este turno. Revisá los horarios actuales.'); return; }
      slots.push({ name: turn.name.trim(), type: 'weekly', days: turn.days, time, duration: turn.duration, layoutId: turn.layoutId || null });
    }
    if (value.slots.length + slots.length > 100) { setError('Se admiten hasta 100 horarios de llegada.'); return; }
    onChange({ slots: [...value.slots, ...slots] }); setError(''); setTurn({ ...turn, name: '', days: [] });
  }
  return <>
    <section className="box"><div className="section-head"><h2>Distribuciones del salón</h2><button type="button" className="secondary" onClick={() => onChange({ layouts: [...layouts, { id: crypto.randomUUID(), name: '', enabled: true, tables: value.tables.map(table => table.name) }] })}>Agregar distribución</button></div><p className="hint">Cada distribución define qué mesas participan de un turno. Los sectores se editan junto a cada mesa.</p>
      {!layouts.length && <p className="hint">Sin distribución específica, el turno usa todas las mesas habilitadas.</p>}
      {layouts.map((layout, i) => <div className="slot" key={layout.id}><div className="row"><label className="field">Nombre<input required value={layout.name} maxLength="100" onChange={e => changeLayout(i, { name: e.target.value })} /></label><label className="days"><input type="checkbox" checked={layout.enabled} onChange={e => changeLayout(i, { enabled: e.target.checked })} />Habilitada</label><button type="button" className="remove" onClick={() => { if (value.slots.some(slot => slot.layoutId === layout.id)) { setError('Desvinculá los turnos antes de quitar esta distribución.'); return; } onChange({ layouts: layouts.filter((_, index) => index !== i) }); }}>Quitar</button></div><div className="days">{value.tables.map(table => <label key={table.name}><input type="checkbox" checked={layout.tables.includes(table.name)} onChange={e => changeLayout(i, { tables: e.target.checked ? [...layout.tables, table.name] : layout.tables.filter(name => name !== table.name) })} />{table.name} · {table.seats} lugares</label>)}</div><p className="hint">{value.tables.filter(table => table.enabled !== false && layout.tables.includes(table.name)).reduce((sum, table) => sum + table.seats, 0)} lugares habilitados</p></div>)}
    </section>
    <section className="box"><h2>Crear turno con varios horarios de llegada</h2><div className="row"><label className="field">Nombre<input value={turn.name} maxLength="100" placeholder="Cena" onChange={e => setTurn({ ...turn, name: e.target.value })} /></label><label className="field">Distribución<select value={turn.layoutId} onChange={e => setTurn({ ...turn, layoutId: e.target.value })}><option value="">Todas las mesas habilitadas</option>{layouts.map(layout => <option key={layout.id} value={layout.id}>{layout.name || 'Sin nombre'}</option>)}</select></label></div><div className="row"><label className="field">Primera llegada<input type="time" value={turn.from} onChange={e => setTurn({ ...turn, from: e.target.value })} /></label><label className="field">Última llegada<input type="time" value={turn.to} onChange={e => setTurn({ ...turn, to: e.target.value })} /></label><label className="field">Intervalo (min)<input type="number" min="15" max="720" value={turn.every} onChange={e => setTurn({ ...turn, every: Number(e.target.value) })} /></label><label className="field">Permanencia (min)<input type="number" min="15" max="720" value={turn.duration} onChange={e => setTurn({ ...turn, duration: Number(e.target.value) })} /></label></div><div className="days">{['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'].map((day, i) => <label key={day}><input type="checkbox" checked={turn.days.includes(i)} onChange={e => setTurn({ ...turn, days: e.target.checked ? [...turn.days, i] : turn.days.filter(value => value !== i) })} />{day}</label>)}</div><button type="button" className="secondary" onClick={addTurn}>Agregar turno</button></section>
    <section className="box"><h2>Reservas por el link público</h2><label className="days"><input type="checkbox" checked={booking.publicEnabled} onChange={e => onChange({ booking: { ...booking, publicEnabled: e.target.checked } })} />Aceptar reservas públicas</label><div className="row"><label className="field">Anticipación máxima (días)<input type="number" required min="1" max="365" value={booking.maxAdvanceDays} onChange={e => onChange({ booking: { ...booking, maxAdvanceDays: Number(e.target.value) } })} /></label><label className="field">Anticipación mínima (min)<input type="number" required min="0" max="10080" value={booking.minNoticeMinutes} onChange={e => onChange({ booking: { ...booking, minNoticeMinutes: Number(e.target.value) } })} /></label><label className="field">Máximo de personas por reserva<input type="number" required min="1" max="100" value={booking.maxPartySize} onChange={e => onChange({ booking: { ...booking, maxPartySize: Number(e.target.value) } })} /></label></div><label className="field">Política de reservas<textarea rows="4" maxLength="2000" value={booking.policy} onChange={e => onChange({ booking: { ...booking, policy: e.target.value } })} /></label></section>
    {error && <p role="alert" className="error">{error}</p>}
  </>;
}
