import {useEffect,useRef,useState} from 'react';
export default function Waitlist({tenantId,user,date}){
 const [entries,setEntries]=useState([]),[form,setForm]=useState({name:'',phone:'',partySize:2,notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const request=useRef(null);
 const change=patch=>{setForm({...form,...patch});request.current=null;};
 useEffect(()=>{let stopped=false;setEntries([]);setError('');user.getIdToken().then(token=>fetch(`/api/tenants/${tenantId}/waitlist?date=${date}`,{headers:{Authorization:`Bearer ${token}`}})).then(async res=>{const result=await res.json();if(!res.ok)throw new Error(result.error);if(!stopped)setEntries(result.entries);}).catch(err=>{if(!stopped)setError(err.message);});return()=>{stopped=true;};},[tenantId,user,date,refresh]);
 async function send(method,body){setBusy(true);setError('');try{const token=await user.getIdToken();const res=await fetch(`/api/tenants/${tenantId}/waitlist`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await res.json();if(!res.ok)throw new Error(result.error);setRefresh(value=>value+1);return true;}catch(err){setError(err.message);return false;}finally{setBusy(false);}}
 async function add(event){event.preventDefault();request.current ||= crypto.randomUUID();if(await send('POST',{...form,date,requestId:request.current})){setForm({name:'',phone:'',partySize:2,notes:''});request.current=null;}}
 return <details className="waitlist"><summary>Lista de espera · {entries.filter(entry=>!['closed','cancelled'].includes(entry.status)).length}</summary><p className="hint">Anotá solicitudes sin disponibilidad. Contactar registra el estado; la comunicación se realiza por separado. Las entradas no ocupan mesas: cargá la reserva antes de cerrarlas.</p><form onSubmit={add}><fieldset disabled={busy}><div className="fields"><label>Nombre<input required minLength="2" maxLength="100" value={form.name} onChange={e=>change({name:e.target.value})}/></label><label>Teléfono<input required type="tel" maxLength="40" value={form.phone} onChange={e=>change({phone:e.target.value})}/></label><label>Personas<input required type="number" min="1" max="100" value={form.partySize} onChange={e=>change({partySize:Number(e.target.value)})}/></label><label>Notas<input maxLength="1000" value={form.notes} onChange={e=>change({notes:e.target.value})}/></label></div><button>Agregar a espera</button></fieldset></form>{entries.map(entry=><article key={entry.id}><strong>{entry.name}</strong> · {entry.partySize} personas · {entry.phone}<p className="hint">{entry.notes} · {({waiting:'En espera',contacted:'Contactado',closed:'Cerrado',cancelled:'Cancelado'})[entry.status]}</p>{!['closed','cancelled'].includes(entry.status)&&<div className="actions">{entry.status==='waiting'&&<button disabled={busy} className="secondary" onClick={()=>send('PATCH',{id:entry.id,status:'contacted'})}>Marcar contactado</button>}<button disabled={busy} className="secondary" onClick={()=>send('PATCH',{id:entry.id,status:'closed'})}>Cerrar entrada</button><button disabled={busy} className="secondary" onClick={()=>send('PATCH',{id:entry.id,status:'cancelled'})}>Cancelar espera</button></div>}</article>)}{error&&<p className="error" role="alert">{error}</p>}<style jsx>{`.waitlist{margin:24px 0;border:1px solid #dfd3c3;border-radius:16px;padding:20px;background:#fffdf8}summary{font-weight:600;cursor:pointer}.fields{display:flex;flex-wrap:wrap;gap:16px;margin-bottom:16px}.fields label{display:flex;flex-direction:column;gap:8px;flex:1 1 180px}fieldset{border:0;padding:0}article{margin:20px 0;padding-top:20px;border-top:1px solid #dfd3c3}`}</style></details>;
}
