import { useEffect,useState } from 'react';
import PrivatePanel from '../components/PrivatePanel';
function Businesses({user}) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[form,setForm]=useState({id:'',name:'',adminEmail:''}),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
  useEffect(()=>{let stopped=false;user.getIdToken().then(token=>fetch('/api/tenants',{headers:{Authorization:`Bearer ${token}`}})).then(async res=>{const result=await res.json();if(!res.ok)throw new Error(result.error);if(!stopped)setData(result);}).catch(err=>{if(!stopped)setError(err.message);});return()=>{stopped=true;};},[user,refresh]);
  async function create(event){event.preventDefault();setBusy(true);setError('');try{const token=await user.getIdToken();const res=await fetch('/api/tenants',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(form)});const result=await res.json();if(!res.ok)throw new Error(result.error);setForm({id:'',name:'',adminEmail:''});setRefresh(value=>value+1);}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <>{!data && !error && <p role="status">Cargando negocios…</p>}{data?.isSuperadmin && <p className="hint">Acceso de superadmin</p>}{data?.isSuperadmin && <details className="box"><summary>Crear negocio</summary><form onSubmit={create}><fieldset disabled={busy}><label className="field">Nombre<input required maxLength="100" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">Identificador para los enlaces<input required pattern="[a-z0-9][a-z0-9-]{0,59}" maxLength="60" placeholder="nombre-del-local" value={form.id} onChange={e=>setForm({...form,id:e.target.value})}/></label><label className="field">Correo de Google del administrador<input type="email" maxLength="160" value={form.adminEmail} onChange={e=>setForm({...form,adminEmail:e.target.value})}/></label><button>{busy?'Creando…':'Crear negocio'}</button></fieldset></form></details>}{data?.tenants.map(tenant=><section className="box" key={tenant.id}><h2>{tenant.name}</h2><nav className="links"><a href={`/admin/${tenant.id}/inicio`}>Admin</a><a href={`/dashboard/${tenant.id}`}>Dashboard</a><a href={`/reservar/${tenant.id}`} target="_blank" rel="noopener noreferrer">Reserva pública ↗</a></nav></section>)}{data && !data.tenants.length && <p>Tu cuenta todavía no tiene un negocio asignado.</p>}{error && <p className="error" role="alert">{error}</p>}</>;
}
export default function Tenants(){return <PrivatePanel title="Mis negocios">{user=><Businesses user={user}/>}</PrivatePanel>;}
